package com.vaultx.userservice.repository;

import com.vaultx.userservice.model.Users;
import com.vaultx.userservice.security.JwtTokenProvider;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.context.bean.override.mockito.MockitoBean;

import java.time.LocalDateTime;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
class UserRepositoryTest {

    @Autowired
    private UserRepository userRepository;

    @MockitoBean
    private JwtTokenProvider jwtTokenProvider;

    @MockitoBean
    private PasswordEncoder passwordEncoder;

    private Users savedUser;

    private Users createUser(String username, String email) {
        Users user = new Users();
        user.setUsername(username);
        user.setEmail(email);
        user.setPasswordHash("hashedpassword");
        user.setFullName("Test User");
        user.setRole("USER");
        user.setKycStatus("PENDING");
        user.setUpdated_at(LocalDateTime.now());
        return user;
    }

    @BeforeEach
    void setUp() {
        userRepository.deleteAll();
        savedUser = userRepository.save(createUser("testuser", "test@example.com"));
    }

    @Test
    void findByEmail_ShouldReturnUser_WhenEmailExists() {
        Optional<Users> found = userRepository.findByEmail("test@example.com");

        assertThat(found).isPresent();
        assertThat(found.get().getEmail()).isEqualTo("test@example.com");
        assertThat(found.get().getUsername()).isEqualTo("testuser");
    }

    @Test
    void findByEmail_ShouldReturnEmpty_WhenEmailDoesNotExist() {
        Optional<Users> found = userRepository.findByEmail("nonexistent@example.com");

        assertThat(found).isEmpty();
    }

    @Test
    void existsByEmail_ShouldReturnTrue_WhenEmailExists() {
        boolean exists = userRepository.existsByEmail("test@example.com");

        assertThat(exists).isTrue();
    }

    @Test
    void existsByEmail_ShouldReturnFalse_WhenEmailDoesNotExist() {
        boolean exists = userRepository.existsByEmail("nonexistent@example.com");

        assertThat(exists).isFalse();
    }

    @Test
    void findById_ShouldReturnUser_WhenIdExists() {
        Optional<Users> found = userRepository.findById(savedUser.getId());

        assertThat(found).isPresent();
        assertThat(found.get().getId()).isEqualTo(savedUser.getId());
    }

    @Test
    void findById_ShouldReturnEmpty_WhenIdDoesNotExist() {
        Optional<Users> found = userRepository.findById(UUID.randomUUID());

        assertThat(found).isEmpty();
    }

    @Test
    void save_ShouldPersistNewUserWithAutoGeneratedId() {
        Users newUser = createUser("newuser", "new@example.com");

        Users persisted = userRepository.save(newUser);

        assertThat(persisted.getId()).isNotNull();
        assertThat(persisted.getCreated_at()).isNotNull();
        assertThat(persisted.getEmail()).isEqualTo("new@example.com");

        Optional<Users> retrieved = userRepository.findById(persisted.getId());
        assertThat(retrieved).isPresent();
    }

    @Test
    void deleteById_ShouldRemoveUser_WhenUserExists() {
        UUID userId = savedUser.getId();
        assertThat(userRepository.findById(userId)).isPresent();

        userRepository.deleteById(userId);

        assertThat(userRepository.findById(userId)).isEmpty();
    }
}
