spring.application.name=bidding-service
server.port=8001

jwt.public-key-path=${JWT_PUBLIC_KEY_PATH:jwt-public.pem}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5001/db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=${SPRING_SQL_INIT_MODE:never}
spring.jpa.defer-datasource-initialization=true

# Kafka
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=true
spring.kafka.consumer.group-id=bidding-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.vaultx.bidding.dto.event.*

grpc.client.user-service.address=static://${GRPC_USER_SERVICE_HOST:localhost}:9000
grpc.client.user-service.negotiation-type=PLAINTEXT
grpc.server.port=9001

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=${ZIPKIN_URL:http://localhost:9411/api/v2/spans}

logging.pattern.level=%5p [${spring.application.name:bidding-service},%X{traceId:-},%X{spanId:-}]